# Oem7 messages; message names and IDs are as they appear in Oem7 manual.
# Correctness of message ID is critical for correct operation.
oem7_msgs:
   # More messages may be added in order to process Oem7 'raw' messages.
 -  LOGLIST: 5
 -  GPSEPHEM: 7
 -  IONUTC: 8
 -  CLOCKMODEL: 16
 -  RAWGPSSUBFRAME: 25
 -  CLOCKSTEERING: 26
 -  VERSION: 37
 -  RAWEPHEM: 41
 -  BESTPOS: 42
 -  RANGE: 43
 -  PSRPOS: 47
 -  PORTSTATS: 72
 -  ALMANAC: 73
 -  RAWALM: 74
 -  TRACKSTAT: 83
 -  RXSTATUS: 93
 -  RXSTATUSEVENT: 94
 -  MATCHEDPOS: 96
 -  BESTVEL: 99
 -  PSRVEL: 100
 -  TIME: 101
 -  RXCONFIG: 128
 -  RANGECMP: 140
 -  RTKPOS: 141
 -  NAVIGATE: 161
 -  AVEPOS: 172
 -  PSRDOP: 174
 -  REFSTATION: 175
 -  VALIDMODELS: 206
 -  RTKVEL: 216
 -  GPALM: 217
 -  GPGGA: 218
 -  GPGLL: 219
 -  GPGRS: 220
 -  GPGSA: 221
 -  GPGST: 222
 -  GPGSV: 223
 -  GPRMB: 224
 -  GPRMC: 225
 -  GPVTG: 226
 -  GPZDA: 227
 -  BESTXYZ: 241
 -  MATCHEDXYZ: 242
 -  PSRXYZ: 243
 -  RTKXYZ: 244
 -  INSATT: 263
 -  INSPOS: 265
 -  INSSPD: 266
 -  INSVEL: 267
 -  RAWIMU: 268
 -  INSATTS: 319
 -  INSPOSS: 321
 -  INSSPDS: 323
 -  INSVELS: 324
 -  RAWIMUS: 325
 -  RAWGPSWORD: 407
 -  PDPPOS: 469
 -  PDPVEL: 470
 -  PDPXYZ: 471
 -  TIMESYNC: 492
 -  INSPVA: 507
 -  INSPVAS: 508
 -  GPGGALONG: 521
 -  RANGEGPSL1: 631
 -  BSLNXYZ: 686
 -  GLOALMANAC: 718
 -  GLOCLOCK: 719
 -  GLORAWALM: 720
 -  GLORAWFRAME: 721
 -  GLORAWSTRING: 722
 -  GLOEPHEMERIS: 723
 -  BESTUTM: 726
 -  GLORAWEPHEM: 792
 -  CORRIMUDATA: 812
 -  CORRIMUDATAS: 813
 -  GLMLA: 859
 -  RTKDOP: 952
 -  HWMONITOR: 963
 -  RAWSBASFRAME: 973
 -  SBAS0: 976
 -  SBAS1: 977
 -  SBAS10: 978
 -  SBAS12: 979
 -  SBAS17: 980
 -  SBAS18: 981
 -  SBAS2: 982
 -  SBAS24: 983
 -  SBAS25: 984
 -  SBAS26: 985
 -  SBAS27: 986
 -  SBAS3: 987
 -  SBAS4: 992
 -  SBAS5: 994
 -  SBAS6: 995
 -  SBAS7: 996
 -  SBAS9: 997
 -  SATVIS2: 1043
 -  GPHDT: 1045
 -  MASTERPOS: 1051
 -  ROVERPOS: 1052
 -  RAWCNAVFRAME: 1066
 -  GALALMANAC: 1120
 -  GALCLOCK: 1121
 -  GALFNAVRAWALMANAC: 1123
 -  GALFNAVRAWEPHEMERIS: 1124
 -  GALINAVRAWALMANAC: 1125
 -  GALINAVRAWEPHEMERIS: 1126
 -  GALIONO: 1127
 -  CHANCONFIGLIST: 1148
 -  PSRSATS: 1162
 -  PSRDOP2: 1163
 -  RTKDOP2: 1172
 -  RTKSATS: 1174
 -  MATCHEDSATS: 1176
 -  PASHR: 1177
 -  BESTSATS: 1194
 -  LBANDTRACKSTAT: 1201
 -  TILTDATA: 1220
 -  PDPSATS: 1234
 -  SOFTLOADSTATUS: 1235
 -  RANGECMP2: 1273
 -  RAIMSTATUS: 1286
 -  ETHSTATUS: 1288
 -  IPSTATUS: 1289
 -  IMURATEPVAS: 1305
 -  GALINAVEPHEMERIS: 1309
 -  GALFNAVEPHEMERIS: 1310
 -  ALIGNBSLNXYZ: 1314
 -  ALIGNBSLNENU: 1315
 -  HEADINGSATS: 1316
 -  VARIABLELEVERARM: 1320
 -  GIMBALLEDPVA: 1321
 -  REFSTATIONINFO: 1325
 -  MODELFEATURES: 1329
 -  QZSSRAWSUBFRAME: 1330
 -  QZSSRAWEPHEM: 1331
 -  ALIGNDOP: 1332
 -  HEADING2: 1335
 -  QZSSEPHEMERIS: 1336
 -  PASSTHROUGH: 1342
 -  SOURCETABLE: 1344
 -  QZSSRAWALMANAC: 1345
 -  QZSSALMANAC: 1346
 -  QZSSIONUTC: 1347
 -  AUTHCODES: 1348
 -  IMURATECORRIMUS: 1362
 -  HEAVE: 1382
 -  PROFILEINFO: 1412
 -  GALFNAVRAWPAGE: 1413
 -  GALINAVRAWWORD: 1414
 -  SBASALMANAC: 1425
 -  BESTGNSSPOS: 1429
 -  BESTGNSSVEL: 1430
 -  RELINSPVA: 1446
 -  SATXYZ2: 1451
 -  TSS1: 1456
 -  INSATTX: 1457
 -  INSVELX: 1458
 -  INSPOSX: 1459
 -  RAWIMUX: 1461
 -  RAWIMUSX: 1462
 -  INSPVAX: 1465
 -  QZSSRAWCNAVMESSAGE: 1530
 -  PPPPOS: 1538
 -  PPPSATS: 1541
 -  PPPDOP2: 1546
 -  BDSALMANAC: 1584
 -  BDSIONO: 1590
 -  BDSCLOCK: 1607
 -  IPSTATS: 1669
 -  BDSRAWNAVSUBFRAME: 1695
 -  BDSEPHEMERIS: 1696
 -  HEADINGRATE: 1698
 -  SYNCHEAVE: 1708
 -  DELAYEDHEAVE: 1709
 -  LBANDBEAMTABLE: 1718
 -  TERRASTARINFO: 1719
 -  VERIPOSINFO: 1728
 -  TERRASTARSTATUS: 1729
 -  VERIPOSSTATUS: 1730
 -  RANGECMP3: 1734
 -  SYNCRELINSPVA: 1743
 -  UPTIME: 1777
 -  IMURATEPVA: 1778
 -  INSUPDATESTATUS: 1825
 -  RADARSTATUS: 1877
 -  INSPVACMP: 1889
 -  INSPVASDCMP: 1890
 -  J1939STATUS: 1907
 -  INSCONFIG: 1945
 -  SAVEDSURVEYPOSITIONS: 1951
 -  INSCALSTATUS: 1961
 -  ITPSDFINAL: 1968
 -  ITFILTTABLE: 1991
 -  PDPDOP2: 1995
 -  PPPDOP: 1997
 -  PDPDOP: 1998
 -  ITBANDPASSBANK: 2022
 -  ITPROGFILTBANK: 2023
 -  DUALANTENNAHEADING: 2042
 -  GPHDTDUALANTENNA: 2045
 -  RTKASSISTSTATUS: 2048
 -  RANGECMP4: 2050
 -  INSSTDEV: 2051
 -  INSSTDEVS: 2052
 -  SAFEMODESTATUS: 2060
 -  ITPSDDETECT: 2063
 -  ITDETECTSTATUS: 2065
 -  WIFIAPSETTINGS: 2093
 -  FILELIST: 2100
 -  FILETRANSFERSTATUS: 2101
 -  FILESYSTEMSTATUS: 2104
 -  NAVICRAWSUBFRAME: 2105
 -  TRANSFERPORTSTATUS: 2114
 -  INSATTQS: 2118
 -  NAVICALMANAC: 2122
 -  NAVICEPHEMERIS: 2123
 -  NAVICIONO: 2124
 -  NAVICSYSCLOCK: 2125
 -  FILESTATUS: 2127
 -  INSSEEDSTATUS: 2129
 -  FILESYSTEMCAPACITY: 2137
 -  LUAFILESYSTEMSTATUS: 2150
 -  LUAFILELIST: 2151
 -  LUASTATUS: 2152
 -  OCEANIXINFO: 2159
 -  OCEANIXSTATUS: 2160
 -  RAWSBASFRAME2: 2185
 -  SATELSTATUS: 2205
 -  WIFISTATUS: 2207
 -  WIFINETLIST: 2210
 -  SATEL4INFO: 2216
 -  SATEL9INFO: 2220
 -  BESTVELX: 2230
 -  USERI2CRESPONSE: 2234
 -  GALCNAVRAWPAGE: 2239
 -  LUAOUTPUT: 2240
 -  PPPSEEDAPPLICATIONSTATUS: 2250
 -  PPPSEEDSTORESTATUS: 2251
 -  QZSSCNAVRAWMESSAGE: 2261
 -  GPSCNAVRAWMESSAGE: 2262
 -  CORRIMUS: 2264
 -  SPRINKLERDATA: 2274
 -  SPRINKLERDATAH: 2276
 -  USERANTENNA: 2282
 -  TECTONICSCOMPENSATION: 2291
 -  PPPDATUMINFO: 2293
 -  GEODETICDATUMS: 2296
 -  DATUMTRANSFORMATIONS: 2298
 -  PSRDATUMINFO: 2300
 -  BESTGNSSDATUMINFO: 2302
 -  PDPDATUMINFO: 2303
 -  RTKDATUMINFO: 2304
 -  BESTDATUMINFO: 2305
 -  TILTSTATUS: 2310
 -  INSVELUSER: 2318
 -  SKCALIBRATESTATUS: 2364
 -  BDSBCNAV1EPHEMERIS: 2371
 -  BDSBCNAV2EPHEMERIS: 2372
 -  BDSBCNAV1RAWMESSAGE: 2373
 -  BDSBCNAV2RAWMESSAGE: 2374
 -  INSDATUMINFO: 2384
