oem7_raw_msgs:
- 5     # LOGLIST
- 7     # GPSEPHEM
- 8     # IONUTC
- 16    # CLOCKMODEL
- 25    # RAWGPSSUBFRAME
- 26    # CLOCKSTEERING
- 37    # VERSION
- 41    # RAWEPHEM
- 42    # BESTPOS
- 43    # RANGE
- 47    # PSRPOS
- 72    # PORTSTATS
- 73    # ALMANAC
- 74    # RAWALM
- 83    # TRACKSTAT
- 93    # RXSTATUS
- 94    # RXSTATUSEVENT
- 96    # MATCHEDPOS
- 99    # BESTVEL
- 100   # PSRVEL
- 101   # TIME
- 128   # RXCONFIG
- 140   # RANGECMP
- 141   # RTKPOS
- 161   # NAVIGATE
- 172   # AVEPOS
- 174   # PSRDOP
- 175   # REFSTATION
- 206   # VALIDMODELS
- 216   # RTKVEL
- 217   # GPALM
- 218   # GPGGA
- 219   # GPGLL
- 220   # GPGRS
- 221   # GPGSA
- 222   # GPGST
- 223   # GPGSV
- 224   # GPRMB
- 225   # GPRMC
- 226   # GPVTG
- 227   # GPZDA
- 241   # BESTXYZ
- 242   # MATCHEDXYZ
- 243   # PSRXYZ
- 244   # RTKXYZ
- 263   # INSATT
- 265   # INSPOS
- 266   # INSSPD
- 267   # INSVEL
- 268   # RAWIMU
- 319   # INSATTS
- 321   # INSPOSS
- 323   # INSSPDS
- 324   # INSVELS
- 325   # RAWIMUS
- 407   # RAWGPSWORD
- 469   # PDPPOS
- 470   # PDPVEL
- 471   # PDPXYZ
- 492   # TIMESYNC
- 507   # INSPVA
- 508   # INSPVAS
- 521   # GPGGALONG
- 631   # RANGEGPSL1
- 686   # BSLNXYZ
- 718   # GLOALMANAC
- 719   # GLOCLOCK
- 720   # GLORAWALM
- 721   # GLORAWFRAME
- 722   # GLORAWSTRING
- 723   # GLOEPHEMERIS
- 726   # BESTUTM
- 792   # GLORAWEPHEM
- 812   # CORRIMUDATA
- 813   # CORRIMUDATAS
- 859   # GLMLA
- 952   # RTKDOP
- 963   # HWMONITOR
- 973   # RAWSBASFRAME
- 976   # SBAS0
- 977   # SBAS1
- 978   # SBAS10
- 979   # SBAS12
- 980   # SBAS17
- 981   # SBAS18
- 982   # SBAS2
- 983   # SBAS24
- 984   # SBAS25
- 985   # SBAS26
- 986   # SBAS27
- 987   # SBAS3
- 992   # SBAS4
- 994   # SBAS5
- 995   # SBAS6
- 996   # SBAS7
- 997   # SBAS9
- 1043  # SATVIS2
- 1045  # GPHDT
- 1051  # MASTERPOS
- 1052  # ROVERPOS
- 1066  # RAWCNAVFRAME
- 1120  # GALALMANAC
- 1121  # GALCLOCK
- 1123  # GALFNAVRAWALMANAC
- 1124  # GALFNAVRAWEPHEMERIS
- 1125  # GALINAVRAWALMANAC
- 1126  # GALINAVRAWEPHEMERIS
- 1127  # GALIONO
- 1148  # CHANCONFIGLIST
- 1162  # PSRSATS
- 1163  # PSRDOP2
- 1172  # RTKDOP2
- 1174  # RTKSATS
- 1176  # MATCHEDSATS
- 1177  # PASHR
- 1194  # BESTSATS
- 1201  # LBANDTRACKSTAT
- 1220  # TILTDATA
- 1234  # PDPSATS
- 1235  # SOFTLOADSTATUS
- 1273  # RANGECMP2
- 1286  # RAIMSTATUS
- 1288  # ETHSTATUS
- 1289  # IPSTATUS
- 1305  # IMURATEPVAS
- 1309  # GALINAVEPHEMERIS
- 1310  # GALFNAVEPHEMERIS
- 1314  # ALIGNBSLNXYZ
- 1315  # ALIGNBSLNENU
- 1316  # HEADINGSATS
- 1320  # VARIABLELEVERARM
- 1321  # GIMBALLEDPVA
- 1325  # REFSTATIONINFO
- 1329  # MODELFEATURES
- 1330  # QZSSRAWSUBFRAME
- 1331  # QZSSRAWEPHEM
- 1332  # ALIGNDOP
- 1335  # HEADING2
- 1336  # QZSSEPHEMERIS
- 1342  # PASSTHROUGH
- 1344  # SOURCETABLE
- 1345  # QZSSRAWALMANAC
- 1346  # QZSSALMANAC
- 1347  # QZSSIONUTC
- 1348  # AUTHCODES
- 1362  # IMURATECORRIMUS
- 1382  # HEAVE
- 1412  # PROFILEINFO
- 1413  # GALFNAVRAWPAGE
- 1414  # GALINAVRAWWORD
- 1425  # SBASALMANAC
- 1429  # BESTGNSSPOS
- 1430  # BESTGNSSVEL
- 1446  # RELINSPVA
- 1451  # SATXYZ2
- 1456  # TSS1
- 1457  # INSATTX
- 1458  # INSVELX
- 1459  # INSPOSX
- 1461  # RAWIMUX
- 1462  # RAWIMUSX
- 1465  # INSPVAX
- 1530  # QZSSRAWCNAVMESSAGE
- 1538  # PPPPOS
- 1541  # PPPSATS
- 1546  # PPPDOP2
- 1584  # BDSALMANAC
- 1590  # BDSIONO
- 1607  # BDSCLOCK
- 1669  # IPSTATS
- 1695  # BDSRAWNAVSUBFRAME
- 1696  # BDSEPHEMERIS
- 1698  # HEADINGRATE
- 1708  # SYNCHEAVE
- 1709  # DELAYEDHEAVE
- 1718  # LBANDBEAMTABLE
- 1719  # TERRASTARINFO
- 1728  # VERIPOSINFO
- 1729  # TERRASTARSTATUS
- 1730  # VERIPOSSTATUS
- 1734  # RANGECMP3
- 1743  # SYNCRELINSPVA
- 1777  # UPTIME
- 1778  # IMURATEPVA
- 1825  # INSUPDATESTATUS
- 1877  # RADARSTATUS
- 1889  # INSPVACMP
- 1890  # INSPVASDCMP
- 1907  # J1939STATUS
- 1945  # INSCONFIG
- 1951  # SAVEDSURVEYPOSITIONS
- 1961  # INSCALSTATUS
- 1968  # ITPSDFINAL
- 1991  # ITFILTTABLE
- 1995  # PDPDOP2
- 1997  # PPPDOP
- 1998  # PDPDOP
- 2022  # ITBANDPASSBANK
- 2023  # ITPROGFILTBANK
- 2042  # DUALANTENNAHEADING
- 2045  # GPHDTDUALANTENNA
- 2048  # RTKASSISTSTATUS
- 2050  # RANGECMP4
- 2051  # INSSTDEV
- 2052  # INSSTDEVS
- 2060  # SAFEMODESTATUS
- 2063  # ITPSDDETECT
- 2065  # ITDETECTSTATUS
- 2093  # WIFIAPSETTINGS
- 2100  # FILELIST
- 2101  # FILETRANSFERSTATUS
- 2104  # FILESYSTEMSTATUS
- 2105  # NAVICRAWSUBFRAME
- 2114  # TRANSFERPORTSTATUS
- 2118  # INSATTQS
- 2122  # NAVICALMANAC
- 2123  # NAVICEPHEMERIS
- 2124  # NAVICIONO
- 2125  # NAVICSYSCLOCK
- 2127  # FILESTATUS
- 2129  # INSSEEDSTATUS
- 2137  # FILESYSTEMCAPACITY
- 2150  # LUAFILESYSTEMSTATUS
- 2151  # LUAFILELIST
- 2152  # LUASTATUS
- 2159  # OCEANIXINFO
- 2160  # OCEANIXSTATUS
- 2185  # RAWSBASFRAME2
- 2205  # SATELSTATUS
- 2207  # WIFISTATUS
- 2210  # WIFINETLIST
- 2216  # SATEL4INFO
- 2220  # SATEL9INFO
- 2230  # BESTVELX
- 2234  # USERI2CRESPONSE
- 2239  # GALCNAVRAWPAGE
- 2240  # LUAOUTPUT
- 2250  # PPPSEEDAPPLICATIONSTATUS
- 2251  # PPPSEEDSTORESTATUS
- 2261  # QZSSCNAVRAWMESSAGE
- 2262  # GPSCNAVRAWMESSAGE
- 2264  # CORRIMUS
- 2274  # SPRINKLERDATA
- 2276  # SPRINKLERDATAH
- 2282  # USERANTENNA
- 2291  # TECTONICSCOMPENSATION
- 2293  # PPPDATUMINFO
- 2296  # GEODETICDATUMS
- 2298  # DATUMTRANSFORMATIONS
- 2300  # PSRDATUMINFO
- 2302  # BESTGNSSDATUMINFO
- 2303  # PDPDATUMINFO
- 2304  # RTKDATUMINFO
- 2305  # BESTDATUMINFO
- 2310  # TILTSTATUS
- 2318  # INSVELUSER
- 2364  # SKCALIBRATESTATUS
- 2371  # BDSBCNAV1EPHEMERIS
- 2372  # BDSBCNAV2EPHEMERIS
- 2373  # BDSBCNAV1RAWMESSAGE
- 2374  # BDSBCNAV2RAWMESSAGE
- 2384  # INSDATUMINFO
